### PR TITLE
Mitigate error caused by Scoop Installation of Spotify

### PR DESCRIPTION
**Pull request by HerXayah**
TLDR:
This mitigates error #3 in a decent and fashionable manner.
One could go and try to find ``Scoop Apps\\Spotify.ink``, which i was unable to pointer-find via 3 tools, although it exists.

### CODE REVIEW

**Comment by NULLYUKI** [comment]
```java
if(this.findInMemory(0, 0x0FFFFFFF, "Scoop Apps".getBytes()) != -1) {
    ADDRESS_OFFSET_TRACK_ID = 0xFEFE8;
}
```
I'm not sure why, but this looks cursed lmao. Kinda got the feeling there would have been a bit of a cleaner way lol But that might work.

I got a few points regarding the commit https://github.com/LabyStudio/java-spotify-api/pull/4/commits/c075e5ccc91731e9ebfb01bad5acd8f8f8633910
- Isn't there a better alternative than `this.findInMemory` ?
- Did you made sure it works for Scoop Spotify **AND** Vanilla Spotify? Because it feels like there is missing something at the part of the code where it checks the memory, I'm not sure if there is some extra code needed to make sure it will continue when it cannot find the Scoop Memory and finds the Vanilla Spotify one or if it will then just continue and work for both versions.

However this looks definitely a bit better than the first commit https://github.com/LabyStudio/java-spotify-api/pull/4/commits/c223c9bf3900ae113303fbc12fcb58751992a58d and was nicely done.
I will properly soon check if this issue also occurs when installing Spotify via [Chocolatey](https://chocolatey.org/). And then also help out finding the correct offset for it.

**Comment by NULLYUKI** [comment]
Also regarding this:
> One could go and try to find `Scoop Apps\\Spotify.ink`, which i was unable to pointer-find via 3 tools, although it exists.

I'm not sure what you mean by that? Are you asking for someone to try and help finding the pointer for that?
Because I'm not sure if this is possible with a `.ink` file, as the offset might always change when the shortcut is created.

The better resolution would be to use the pointer from the `.exe` file that the shortcut is opening.

**Comment by HerXayah** [comment]
> Also regarding this:
> 
> > One could go and try to find `Scoop Apps\\Spotify.ink`, which i was unable to pointer-find via 3 tools, although it exists.
> 
> I'm not sure what you mean by that? Are you asking for someone to try and help finding the pointer for that? Because I'm not sure if this is possible with a `.ink` file, as the offset might always change when the shortcut is created.
> 
> The better resolution would be to use the pointer from the `.exe` file that the shortcut is opening.

image
image

**Comment by NULLYUKI** [comment]
> > Also regarding this:
> > > One could go and try to find `Scoop Apps\\Spotify.ink`, which i was unable to pointer-find via 3 tools, although it exists.
> > 
> > 
> > I'm not sure what you mean by that? Are you asking for someone to try and help finding the pointer for that? Because I'm not sure if this is possible with a `.ink` file, as the offset might always change when the shortcut is created.
> > The better resolution would be to use the pointer from the `.exe` file that the shortcut is opening.
> 
> image image

Ahhhhh, ok now I understand it. I first thought you meant the `Spotify.ink` file itself lmao.
But if you are just trying to find the offset for the `Scoop Apps\Spotify.ink` value Then it totally will be possible via Cheat Engine.
Because I have seen in the past programs using the Offset of such values for different kind of stuff.

Also can you please tell what file you put into Cheat Engine to find the `Scoop Apps\Spotify.ink` value? This would help quickly finding the value in the correct file and starting with the search for the offset.

I will be trying to start today or tomorrow finding the offset.👍

Thank you for the great in depth research of finding these values and offsets. This is helping a lot getting the offset.
So I should be getting the correct pointer quickly with my past knowledge of the usage with Cheat Engine and finding pointers.

I also already got a plan how the offset can be found correctly.👍

**Comment by NULLYUKI** [comment]
https://github.com/LabyStudio/java-spotify-api/pull/4/commits/8ee6bf5ac2c654eb5dd3a86ea4d53f854ae38692

Using a Array list for the offsets was also an idea I had but not sure, if this should be used.
But good to see that this was a good idea and is being implemented like that now.

**Comment by LabyStudio** [comment]
Thanks for the contribution!

**Pull request merged**
