### PR TITLE
Fix API on latest Spotify Update

### PR DESCRIPTION
**Pull request by HerXayah**

### CODE REVIEW

**Comment by HerXayah** [comment]
Dont merge yet. Updating 32-Bit rn

**Comment by HerXayah** [comment]
Ive noticed that the Offset of the 32-Bit Version isnt beeing used anymore. Only when i uncomment the 64-Bit offset.

EDIT 1:
On further investigation it seems the for-clause never switches the address
image

**Comment by HerXayah** [comment]
Now im facing the issue that the Ingame Addon, when copying the Lib of this Project in, doesnt really like when a new song plays.

EDIT:
On reversal of my commit ive observed the same behaviour.
Spotify is disconnecting everytime the new song starts.
image

EDIT 2:
32-Bit now returns an invalid Playback Address.

EDIT 3:
32-Bit, when uncommented 64-Bit is present, works fine with playback and changing of song. Wtf is going on here?
image


Yep what i thought.
64-Bit is broken. The offset is right, changing song makes it dosconnect everytime.

**Comment by LabyStudio** [comment]
Thanks for the help!

**Pull request merged**
