### PR TITLE
Add Linux implementation

### PR DESCRIPTION
**Pull request by holybaechu**
Adds Linux implementation using **[MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/)** and DBus

Will work on almost all distros that uses systemd (Almost all distros use systemd)

### CODE REVIEW

**Comment by holybaechu** [comment]
I would appreciate it if LabyStudio update his Spotify addon on FlintMC along with this PR if it gets merged

**Comment by holybaechu** [comment]
I’m currently writing DBus parser to use this without playerctl installed. 
Might take long time

**Comment by holybaechu** [comment]
I’m JavaScript developer so I may not use Java naming conventions.
I will try to refactor the variables and classes

**Comment by LabyStudio** [comment]
Hey, nice work!
Could you wrap the dbus communication in an extra class? Like the AppleScript implementation for macOS.

**Comment by holybaechu** [comment]
> Hey, nice work!
> Could you wrap the dbus communication in an extra class? Like the AppleScript implementation for macOS.

I warpped D-Bus communication to MPRISCommunicator class now.

Also LabyStudio, Please note that this only works with Linux distros that uses systemd.
Here is a [list of Linux distros that doesn't use systemd](https://en.wikipedia.org/wiki/Category:Linux_distributions_without_systemd). (Ex: Android)

**Comment by LabyStudio** [comment]
I've changed the structure of the dbus & mpris api, but it may not work anymore because I'm on Windows and can't test it properly. I guess you will have to debug it really quick and adjust the parsing to fix the issues

**Comment by holybaechu** [comment]
I don't know exactly why but runtime.exec didn't work well with dbus-send in past and now.
I'll edit the code to use ProcessBuilder probably tomorrow.

**Comment by LabyStudio** [comment]
I managed to connect to the dbus of my WSL and test the Linux implementation under Windows.
It works without any problems! It would be good to know if it works on your system too!

**Comment by holybaechu** [comment]
Note that position unit is in seconds, not milliseconds.
I edited getTrackLength method and the if condition to make it work.
Everything else is working fine.

**Comment by holybaechu** [comment]
Nevermind, It was in milliseconds.
But I don't know why the position is not updating frequently.
I'll look into this issue right now.

**Comment by holybaechu** [comment]
https://github.com/LabyStudio/java-spotify-api/assets/66154521/b4c5b8ac-bd5a-4df3-a74e-168f41dd733f

I ported this PR to the Spotify addon and this is happening.
Whenever i do any action, the timestamp goes away for like 1 seconds and appears again and when i pause and play the song, It flickers.

Any solutions to this?

**Comment by holybaechu** [comment]
I tested this on my actual LabyMod config that i use when playing, And whenever i pause and play, The widget disappers.

**Comment by holybaechu** [comment]
I tested it and this is the output when I play and pause:
```
Connected to Spotify!
Track changed: [7a5Z1tB8JiO5zSDIdVuuf3] 제발 - Kim Bum Soo (4m 41s)
Loaded track cover: 640x640
Position changed: 1m 18s of 4m 41s (27%)
Triggered Play/Pause Media key
Disconnected: Invalid variant: 
Connected to Spotify!
Song started playing
Position changed: 1m 20s of 4m 41s (28%)
Triggered Play/Pause Media key
Disconnected: Invalid variant: 
Connected to Spotify!
Song stopped playing

```

**Comment by holybaechu** [comment]
It was because when sending dbus-send to call function, It does not print anything except for `method ~` so the result of `builder.toString()` in method DBusSend.send() would be empty. So i added if condition to check if the builder.toString()'s result is empty or not.

**Comment by LabyStudio** [comment]
The onPositionChanged in the listener you are using should not be used as an indicator of its actual current position. It is actually an indicator of a change in the current "flow" or "direction".

The api.getPosition() function automatically calculates Spotify's current position by adding the elapsed time to the last known position.
It is implemented in such a way that it provides a consistent estimate of the current position without flooding the application with requests.

If for some reason your position still jumps, that must be a different problem. I just tested it again and it works fine for me.
Try removing the debug message in onSync that I just added. That's the actual position you want to keep track of.

**Comment by holybaechu** [comment]
Ooh so the last known position works like offset for getting current position.
LGTM!

**Comment by LabyStudio** [comment]
Nice! Ready for merge?

**Comment by holybaechu** [comment]
Yup

**Comment by LabyStudio** [comment]
Thank you for your awesome contribution!

**Comment by holybaechu** [comment]
> Thank you for your awesome contribution!

No problem!
Also, Please update the Spotify addon as soon as possible, Thanks!

**Pull request merged**
